version: '3'
services:
 plex:
   container_name: plex
   image: plexinc/pms-docker
   restart: unless-stopped
   ports:
     - 32400:32400/tcp
     - 3005:3005/tcp
     - 8324:8324/tcp
     - 32469:32469/tcp
     - 1900:1900/udp
     - 32410:32410/udp
     - 32412:32412/udp
     - 32413:32413/udp
     - 32414:32414/udp
   environment:
     - TZ=Europe/Zurich
     - PLEX_CLAIM=Z4szTvSYzN7tfjEsUyDz
     - ADVERTISE_IP=http://192.168.50.2:32400/
   hostname: Vagrant_VM
   volumes:
     - /config/plex:/config
     - /media:/data
     - /config/plex/transcode
 
 sonarr: 
    container_name: sonarr
    image: linuxserver/sonarr
    restart: unless-stopped
    ports:
        - 8989:8989/tcp
    environment:
        - TZ=Europe/Zurich
        - PGID=1000
        - PUID=1000
    volumes:
        - /config/sonarr:/config
        - /media/series:/tv
        - /media/downloads:/downloads
 
 radarr: 
    container_name: radarr
    image: linuxserver/radarr
    restart: unless-stopped
    ports:
        - 7878:7878/tcp
    environment:
        - TZ=Europe/Zurich
        - PGID=1000
        - PUID=1000
    volumes:
        - /config/radarr:/config
        - /media/movies:/movies
        - /media/downloads:/downloads
 
 portainer:
    image: portainer/portainer-ce
    container_name: portainer
    restart: unless-stopped
    ports:
        - 9000:9000
    command: -H unix:///var/run/docker.sock
    volumes:
        - /portainer/data:/data
        - /var/run/docker.sock:/var/run/docker.sock
    network_mode: bridge
    